### ISSUE TITLE
Not published on NPM

### ISSUE THREAD

**Issue by ernanirst** [Netflix-Skunkworks/atlas-node-client#33]
Couldn't find a version of `atlasclient` on npm :(

It would be great if someone could publish there.

**Comment by dmuino** [comment]
Take a look at [spectator-js](https://github.com/Netflix/spectator-js/) and [spectator-js-nodejsmetrics](https://github.com/Netflix-Skunkworks/spectator-js-nodejsmetrics). They are published on npm as nflx-spectator and nflx-spectator-nodejsmetrics

atlasclient is more or less deprecated at this time.
